---

- name: Create MARIADB Volume
  become: true
  file:
    path: "{{ MARIADB_VOLUME }}"
    owner: 999
    state: directory

- name: Create NEXTCLOUD Docker Network
  docker_network:
    name: "{{ NEXTCLOUD_NETWORK }}"
    scope: swarm
    driver: overlay

- name: Create MEDIA Docker Network
  docker_network:
    name: "{{ MEDIA_NETWORK }}"
    scope: swarm
    driver: overlay

- name: Deploy Cloud Services
  docker_stack:
    state: present
    name: cloud
    compose:
      - "{{ STG_DIR }}/nextcloud-compose.yml"
      - "{{ STG_DIR }}/collabora-compose.yml"
      - "{{ STG_DIR }}/nginx-compose.yml"

- name: Deploy Media Services
  docker_stack:
    state: present
    name: media
    compose:
      - "{{ STG_DIR }}/jellyfin-compose.yml"

- name: Remove Staged Files
  shell: rm -rf /tmp/.*-compose.yml