STG_DIR: "/tmp/stg"
NEXTCLOUD_NETWORK: "nextcloud_net"

# DOCKER
docker_users: ["{{ ansible_user_id }}"]

PORTS:
  NEXTCLOUD: 443
  COLLABORA: 9980
  WIREGUARD: 51820

NGINX_IMAGE: "nginx"
MARIADB_IMAGE: "mariadb"
NEXTCLOUD_IMAGE: "nextcloud"
COLLABORA_IMAGE: "collabora/code"

NGINX_VERSION: "1.21.4"
MARIADB_VERSION: "10.5.13"
NEXTCLOUD_VERSION: "23.0.0-fpm"
COLLABORA_VERSION: "21.11.0.6.1"

# VOLUMES
MARIADB_VOLUME: "{{ ansible_env.HOME }}/mariadb"
NEXTCLOUD_VOLUME: "{{ ansible_env.HOME }}/nextcloud"
NGINX_VOLUME: "{{ ansible_env.HOME }}/nginx"
COLLABORA_VOLUME: "{{ ansible_env.HOME }}/collabora"

# CERT
CERT_PATH: "/etc/ssl/certs"

###############
## ENCRYPTED ##
###############

# MARIADB
#MYSQL_DATABASE: ""
#MYSQL_USER: ""
#MYSQL_ROOT_PASSWORD: ""
#MYSQL_PASSWORD: ""

# COLLABORA
#COLLABORA_PASSWORD: ""
#COLLABORA_USERNAME: ""
