# LOGGING
LOGGING_LEVEL_NUMERIC: 0

LOGGING_LEVEL_NGINX_VALUES: ['debug', 'info', 'warn', 'error']
LOGGING_LEVEL_NEXTCLOUD_VALUES: ['debug', 'info', 'warn', 'error']     # NUMERIC VALUE IS REQUIRED BY CONFIG FILE
LOGGING_LEVEL_COLLABORA_VALUES: ['debug', 'information', 'warning', 'error']
LOGGING_LEVEL_REDIS_VALUES: ['debug', 'verbose', 'notice', 'warning']

STG_DIR: "/tmp/stg"

# DOCKER
docker_users: ["{{ ansible_user_id }}"]

NEXTCLOUD_NETWORK: "cloud_net"

PORTS:
  NEXTCLOUD: 443

NGINX_IMAGE: "nginx"
REDIS_IMAGE: "redis"
MARIADB_IMAGE: "mariadb"
NEXTCLOUD_IMAGE: "nextcloud"
COLLABORA_IMAGE: "collabora/code"

NGINX_VERSION: "1.23.2-alpine"
REDIS_VERSION: "alpine3.16"
MARIADB_VERSION: "10.9.3"
NEXTCLOUD_VERSION: "25.0.0-fpm-alpine"
COLLABORA_VERSION: "22.05.7.2.1"

# VOLUMES
MARIADB_VOLUME: "{{ ansible_env.HOME }}/mariadb"
NEXTCLOUD_VOLUME: "{{ ansible_env.HOME }}/nextcloud"
NGINX_VOLUME: "{{ ansible_env.HOME }}/nginx"
COLLABORA_VOLUME: "{{ ansible_env.HOME }}/collabora"

# CERT
CERT_PATH: "/etc/ssl/certs"

###############
## ENCRYPTED ##
###############

# MARIADB
#MYSQL_DATABASE: ""
#MYSQL_USER: ""
#MYSQL_ROOT_PASSWORD: ""
#MYSQL_PASSWORD: ""

# COLLABORA
#COLLABORA_PASSWORD: ""
#COLLABORA_USERNAME: ""

# SSL
#CHAIN_SSL_CERT: ""
#PUBLIC_SSL_KEY: ""
#PRIVATE_SSL_KEY: ""