# LOGGING
LOGGING_LEVEL_NUMERIC: 3

LOGGING_LEVEL_NGINX_VALUES: ['debug', 'info', 'warn', 'error']
LOGGING_LEVEL_NEXTCLOUD_VALUES: ['debug', 'info', 'warn', 'error']     # NUMERIC VALUE IS REQUIRED BY CONFIG FILE
LOGGING_LEVEL_COLLABORA_VALUES: ['debug', 'information', 'warning', 'error']
LOGGING_LEVEL_REDIS_VALUES: ['debug', 'verbose', 'notice', 'warning']

STG_DIR: "/tmp"

# DOCKER
docker_users: ["{{ ansible_user_id }}"]

NEXTCLOUD_NETWORK: "cloud"
MEDIA_NETWORK: "media"

PORTS:
  NEXTCLOUD: 443
  JELLYFIN: 8096
  JELLYFIN_HTTPS: 8097


# IMAGES
NGINX_IMAGE: "nginx"
REDIS_IMAGE: "redis"
MARIADB_IMAGE: "mariadb"
NEXTCLOUD_IMAGE: "nextcloud"
COLLABORA_IMAGE: "collabora/code"
JELLYFIN_IMAGE: "linuxserver/jellyfin"

NGINX_VERSION: "1.23.3-alpine"
REDIS_VERSION: "alpine3.17"
MARIADB_VERSION: "10.11.2"
NEXTCLOUD_VERSION: "25.0.4-fpm-alpine"
COLLABORA_VERSION: "22.05.10.8.1"
JELLYFIN_VERSION: "10.8.9"

# VOLUMES
MARIADB_VOLUME: "{{ ansible_env.HOME }}/mariadb"
NEXTCLOUD_VOLUME: "{{ ansible_env.HOME }}/nextcloud"
NGINX_VOLUME: "{{ ansible_env.HOME }}/nginx"
COLLABORA_VOLUME: "{{ ansible_env.HOME }}/collabora"
JELLYFIN_VOLUME: "{{ ansible_env.HOME }}/jellyfin"
JELLYFIN_MEDIA_VOLUME: "/media/seagate"

# CERT
CERT_PATH: "/etc/ssl/certs"


###############
## ENCRYPTED ##
###############

# MARIADB
#MYSQL_DATABASE: ""
#MYSQL_USER: ""
#MYSQL_ROOT_PASSWORD: ""
#MYSQL_PASSWORD: ""

# COLLABORA
#COLLABORA_PASSWORD: ""
#COLLABORA_USERNAME: ""

# SSL
#CHAIN_SSL_CERT: ""
#PUBLIC_SSL_KEY: ""
#PRIVATE_SSL_KEY: ""