---

- name: Create Stagging Directory
  file:
    path: "{{ STG_DIR }}"
    state: directory

- name: Upgrade Raspberry OS
  become: true
  register: upgrade_os
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install PIP jsondiff
  pip:
    name: jsondiff