---

- name: Install Prequesites
  become: true
  apt:
    update_cache: yes
    pkg:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3
      - python3-pip

- name: Install Docker Compose
  pip:
    name: docker-compose