---

- name: Fetch Docker Install Script
  get_url:
    url: https://get.docker.com
    dest: "{{ STG_DIR }}/docker_install.sh"

- name: Install Docker
  become: true
  shell: bash {{ STG_DIR }}/docker_install.sh

- name: Create Docker Group
  become: true
  user:
    name: docker
    state: present

- name: Add Docker User to Docker Group
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  register: docker_group

- name: Reset ssh connection to allow user changes to affect ansible user
  meta:
    reset_connection