---

- name: Create NGINX Volume
  file:
    path: "{{ NGINX_VOLUME }}"
    group: www-data
    state: directory

- name: Copy NGINX Configuration File
  become: true
  template:
    src: nginx.conf.j2
    dest: "{{ NGINX_VOLUME }}/nginx.conf"
    owner: www-data
    group: www-data
    follow: yes