---

- name: Create NEXTCLOUD Volume
  become: true
  file:
    path: "{{ NEXTCLOUD_VOLUME }}"
    owner: 82
    state: directory

- name: Copy OP-CACHE Configuration File
  become: true
  template:
    src: op-cache.conf.j2
    dest: "{{ NEXTCLOUD_VOLUME }}/op-cache.conf"
    owner: 82
    follow: yes

- name: Copy PHP-FPM Configuration File
  become: true
  template:
    src: php-fpm.conf.j2
    dest: "{{ NEXTCLOUD_VOLUME }}/php-fpm.conf"
    owner: 82
    follow: yes

- name: Stage Docker Compose File
  template:
    src: docker-compose.yml.j2
    dest: "{{ STG_DIR }}/nextcloud-compose.yml"