---

- name: Remove CLOUD Services
  docker_stack:
    state: absent
    name: cloud
    compose:
      - "{{ STG_DIR }}/nextcloud-compose.yml"
      - "{{ STG_DIR }}/collabora-compose.yml"
      - "{{ STG_DIR }}/nginx-compose.yml"

- name: Remove MEDIA Services
  docker_stack:
    state: absent
    name: media
    compose:
      - "{{ STG_DIR }}/jellyfin-compose.yml"