---

- name: Create MARIADB Storage
  file:
    path: "{{ MARIADB_VOLUME }}"
    state: directory

- name: Create NEXTCLOUD Storage
  file:
    path: "{{ NEXTCLOUD_VOLUME }}"
    state: directory

- name: Stage Docker Compose File
  template:
    src: docker-compose.yml.j2
    dest: "{{ stg_dir }}/nextcloud-compose.yml"

- name: Create Docker Network
  docker_network:
    name: "{{ nextcloud_network }}"

- name: Pull NGINX docker image
  docker_image:
    name: "{{ NGINX_IMAGE }}:{{ NGINX_VERSION }}"
    source: pull
    pull:
      platform: arm64

- name: Pull MARIADB docker image
  docker_image:
    name: "{{ MARIADB_IMAGE }}:{{ MARIADB_VERSION }}"
    source: pull
    pull:
      platform: arm64

- name: Pull NEXTCLOUD docker image
  docker_image:
    name: "{{ NEXTCLOUD_IMAGE }}:{{ NEXTCLOUD_VERSION }}"
    source: pull
    pull:
      platform: arm64

- name: Pull COLLABORA docker image
  docker_image:
    name: "{{ COLLABORA_IMAGE }}:{{ COLLABORA_VERSION }}"
    source: pull
    pull:
      platform: arm64