---

- name: Create MARIADB Volume
  become: true
  file:
    path: "{{ MARIADB_VOLUME }}"
    owner: 999
    state: directory

- name: Stage Docker Compose File
  template:
    src: docker-compose.yml.j2
    dest: "{{ STG_DIR }}/nextcloud-compose.yml"

- name: Pull NGINX Docker Image
  docker_image:
    name: "{{ NGINX_IMAGE }}:{{ NGINX_VERSION }}"
    source: pull
    pull:
      platform: arm64

- name: Pull MARIADB Docker Image
  docker_image:
    name: "{{ MARIADB_IMAGE }}:{{ MARIADB_VERSION }}"
    source: pull
    pull:
      platform: arm64

- name: Pull REDIS Docker Image
  docker_image:
    name: "{{ REDIS_IMAGE }}:{{ REDIS_VERSION }}"
    source: pull
    pull:
      platform: arm64

- name: Pull NEXTCLOUD Docker Image
  docker_image:
    name: "{{ NEXTCLOUD_IMAGE }}:{{ NEXTCLOUD_VERSION }}"
    source: pull
    pull:
      platform: arm64

- name: Pull COLLABORA Docker Image
  docker_image:
    name: "{{ COLLABORA_IMAGE }}:{{ COLLABORA_VERSION }}"
    source: pull
    pull:
      platform: arm64