---

- name: Create NGINX Volume
  file:
    path: "{{ NGINX_VOLUME }}"
    state: directory

- name: Copy NGINX Configuration File
  become: true
  template:
    src: nginx.conf.j2
    dest: "{{ NGINX_VOLUME }}/nginx.conf"
    follow: yes

- name: Stage NGINX Docker Compose File
  template:
    src: docker-compose.yml.j2
    dest: "{{ STG_DIR }}/nginx-compose.yml"