---

- name: Create COLLABORA Volume
  become: true
  file:
    path: "{{ COLLABORA_VOLUME }}"
    owner: 104
    state: directory

- name: Copy Coolwsd Configuration File
  become: true
  template:
    src: coolwsd.xml.j2
    dest: "{{ COLLABORA_VOLUME }}/coolwsd.xml"
    owner: 104
    follow: yes