---

- name: Prepare Environment
  hosts: raspberry_pi
  roles:
    - prepare-env
    - prepare-docker
    - prepare-cert
  tags:
    - setup

- name: Remove Services
  hosts: raspberry_pi
  vars_files:
    - "vaults/all_configs.yml"
  roles:
    - remove-services
  tags:
    - remove

- name: Deploy Services
  hosts: raspberry_pi
  vars_files:
    - "vaults/all_configs.yml"
  roles:
    - deploy-collabora
    - deploy-nginx
    - deploy-nextcloud
    - deploy-jellyfin
    - deploy
  tags:
    - deploy