---

- name: Create COLLABORA Volume
  become: true
  file:
    path: "{{ COLLABORA_VOLUME }}"
    owner: 104
    state: directory

- name: Copy Coolwsd Configuration File
  become: true
  template:
    src: coolwsd.xml.j2
    dest: "{{ COLLABORA_VOLUME }}/coolwsd.xml"
    owner: 104
    follow: yes

- name: Stage COLLABORA Docker Compose File
  template:
    src: docker-compose.yml.j2
    dest: "{{ STG_DIR }}/collabora-compose.yml"